# Build stage
FROM maven:3.9.4-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/CompactDiscRestDataBoot-0.0.1-SNAPSHOT.jar app.jar
COPY src/main/resources/application-docker.properties /app/application-docker.properties

ENV JAVA_OPTS=""
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Dspring.config.location=file:/app/application-docker.properties -jar app.jar"]
