version: '3.0'
services:
   cddb:
     container_name: cd-db
     build:
       context: .
       dockerfile: Dockerfile-mysql
     image: cd/mysql:1.0.0
     # Add back in if you want to connect from sql workbench on host
     #ports:
     #  - "3306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: secret123
       MYSQL_DATABASE: conygre

   cd:
     container_name: cd-server
     build:
       context: .
       dockerfile: Dockerfile-cd-server
     image: cd/cd-server:1.0.0
     depends_on:
       - cddb
     ports:
       - "8080:8080"
     restart: always
